### ISSUE TITLE
Cannot select iTunes playlists in iFetchLyrics

### ISSUE THREAD

**Issue by dastefster** [MacGarfield/iFetchLyrics#1]
None of my iTunes playlists are appearing in iFetchLyrics' dropdown menu.

- iFetchLyrics v1.8
- macOS 10.14.3
- iTunes v12.9.2.5

**Comment by DasBlatz** [comment]
Same for on Mojave there is a permission needed I think

**Comment by MacGarfield** [comment]
thanks it is a mojave permission issue

should be fixed in version 1.9 along with a couple of other issues
